export const UPDATE_SIGNUP_FORM: string = 'UPDATE-SIGNUP-FORM'
export const UPDATE_LOGIN_FORM: string = 'UPDATE-LOGIN-FORM'
export const SET_LOADING: string = 'SET-LOADING'
export const SET_ERROR: string = 'SET-ERROR'
export const DELETE_SUCCESS_MESSAGE: string = 'DELETE-SUCCESS-MESSAGE'
export const SIGNUP: string = 'SIGNUP'
export const LOGIN: string = 'LOGIN'
export const SET_USER: string = 'SET-USER'
