export const SET_LOADING: string = 'SET-LOADING'
export const SET_POSTS: string = 'SET-POSTS'
export const SET_LIKE: string = 'SET-LIKE'
export const UPDATE_FORM: string = 'UPDATE-FORM'
export const ADD_POST: string = 'ADD-POST'
